# Generated by Django 4.1 on 2023-02-13 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scout", "0001_initial"),
        ("fantascout", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoutCompleteTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("checked", models.BooleanField(default=False)),
                (
                    "scout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="scout.scout"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fantascout.fantatask",
                    ),
                ),
            ],
        ),
    ]
