# Generated by Django 4.1 on 2023-02-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantascout", "0002_scoutcompletetask"),
    ]

    operations = [
        migrations.AddField(
            model_name="fantatask",
            name="personal",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
