# Generated by Django 4.1 on 2023-02-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scout", "0002_remove_scout_name_remove_scout_surname_scout_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("body", models.TextField()),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "authors",
                    models.ManyToManyField(blank=True, null=True, to="scout.scout"),
                ),
            ],
        ),
    ]
