# Generated by Django 4.1 on 2023-02-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scout", "0002_remove_scout_name_remove_scout_surname_scout_user_and_more"),
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="authors",
            field=models.ManyToManyField(blank=True, to="scout.scout"),
        ),
    ]
