# Generated by Django 4.1 on 2024-01-14 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="date",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="scoutpartecipation",
            name="date",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
