# Generated by Django 4.1 on 2023-02-19 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scout", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scout",
            name="name",
        ),
        migrations.RemoveField(
            model_name="scout",
            name="surname",
        ),
        migrations.AddField(
            model_name="scout",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scout",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
