# Generated by Django 4.1 on 2023-02-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scout", "0002_remove_scout_name_remove_scout_surname_scout_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scout",
            name="name",
            field=models.CharField(default="Filo", max_length=20),
            preserve_default=False,
        ),
    ]
